#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" && "$1" != '--'* ]]; then
  URL="$1"
  shift
else
  URL="$(grep 'openapi_spec_url' .stats.yml | cut -d' ' -f2)"
fi

# Check if the URL is empty
if [ -z "$URL" ]; then
  echo "Error: No OpenAPI spec path/url provided or found in .stats.yml"
  exit 1
fi

echo "==> Starting mock server with URL ${URL}"

# Run steady mock on the given spec
if [ "$1" == "--daemon" ]; then
  npm exec --package=@stdy/cli@0.15.1 -- steady --host 127.0.0.1 -p 4010 --validator-query-array-format=brackets --validator-query-object-format=brackets "$URL" &> .stdy.log &

  # Wait for server to come online
  echo -n "Waiting for server"
  while ! grep -q "ERROR\|Steady server listening on" ".stdy.log" ; do
    echo -n "."
    sleep 0.1
  done

  if grep -q "ERROR" ".stdy.log"; then
    cat .stdy.log
    exit 1
  fi

  echo
else
  npm exec --package=@stdy/cli@0.15.1 -- steady --host 127.0.0.1 -p 4010 --validator-query-array-format=brackets --validator-query-object-format=brackets "$URL"
fi
